baseurl = "http://192.168.1.36/"
languageCode = "en-us"
theme = "terminal"
paginate = 5

[params]
  contentTypeName = "post"
  themeColor = "green"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = true

[languages]
  [languages.en]
    title = "Proyecto Integración 2021"
    subtitle = "Proyecto para el módulo de Integración 2021."
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "IES Siete Palmas"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
